package com.helpinghands.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACTS".
 */
public class Contacts {

    private Long id;
    /** Not-null value. */
    private String Name;
    private String PhonuNumber;
    private String Photo;

    public Contacts() {
    }

    public Contacts(Long id) {
        this.id = id;
    }

    public Contacts(Long id, String Name, String PhonuNumber, String Photo) {
        this.id = id;
        this.Name = Name;
        this.PhonuNumber = PhonuNumber;
        this.Photo = Photo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    public String getPhonuNumber() {
        return PhonuNumber;
    }

    public void setPhonuNumber(String PhonuNumber) {
        this.PhonuNumber = PhonuNumber;
    }

    public String getPhoto() {
        return Photo;
    }

    public void setPhoto(String Photo) {
        this.Photo = Photo;
    }

}
